image: Visual Studio 2019 # образ для сборки

environment:
  nodejs_version: "18"

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name ns-morozova
  - git config --global user.email ns_morozova@mail.ru
  - echo "https://%GITHUB_TOKEN%:x-oauth-basic@github.com" > "%HOMEDRIVE%%HOMEPATH%\.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose